// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwJBVkQlQzJWEggGh7srBN1J6FtRhhvCs',
    appId: '1:750664799209:web:88bfef4b413d90468bb178',
    messagingSenderId: '750664799209',
    projectId: 'flutter-phone-auth-d2902',
    authDomain: 'flutter-phone-auth-d2902.firebaseapp.com',
    storageBucket: 'flutter-phone-auth-d2902.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD36dsjfnRDPsUiyl0kpxFmnhRdyfJV5kw',
    appId: '1:750664799209:android:987a30ac4c2d98bd8bb178',
    messagingSenderId: '750664799209',
    projectId: 'flutter-phone-auth-d2902',
    storageBucket: 'flutter-phone-auth-d2902.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEi930cqtxXoUN2ffKWqris9b4k4vOGo4',
    appId: '1:750664799209:ios:0fafaad91e0771608bb178',
    messagingSenderId: '750664799209',
    projectId: 'flutter-phone-auth-d2902',
    storageBucket: 'flutter-phone-auth-d2902.appspot.com',
    iosClientId: '750664799209-77srfcsq8lhjoroj8f7l9it449r2rdsh.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEi930cqtxXoUN2ffKWqris9b4k4vOGo4',
    appId: '1:750664799209:ios:90ed13ee33f2e1f08bb178',
    messagingSenderId: '750664799209',
    projectId: 'flutter-phone-auth-d2902',
    storageBucket: 'flutter-phone-auth-d2902.appspot.com',
    iosClientId: '750664799209-g9us749bq24gtq3nekfhbvsd2muo29o5.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth.RunnerTests',
  );
}
